# Generated by Django 3.2.1 on 2021-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
    ]
